### ISSUE TITLE
sendAutorizeRequest - Callback - Sólo posee AnswerKey y necesito RequestKey

### ISSUE THREAD

**Issue by elgambet** [TodoPago/SDK-Node.js#11]
Definiendo los callbacks en el método **sendAutorizeRequest** mediante los parámetros **URL_OK** y **URL_ERROR** el usuario es redirigido luego de completar los datos de la tarjeta de crédito con un único parámetro **(Answer)**.

```
Ejemplo de redirección:
http://localhost:3001/payments/todopago/success?Answer=29028b99-e128-3c5a-e53d-189e83d5a44c). 
```

El problema radica que su método **getAnswer** necesita de **AnswerKey** y **RequestKey** por lo que no tengo forma de saber a que pago o request está relacionado el request recibido.

_Por lo que mi pregunta es:_

¿Necesito definir algo extra en el método sendAutorizeRequest para recibir el RequestKey?

_Y si la respuesta es negativa:_

¿Puede **configurar** entidades dentro del método **sendAutorizeRequest** que serán concatenadas a Answer en la respuesta?

**Comment by damianwajser** [comment]
Te respondo en varios puntos:

1) por un lado el requestKey te lo devuelve el sendAuthorizeRequest (este dato te lo guardas en tu base de datos o en la session del usuario).
2) en al url de callback el parametro Answer es el answerKey.

Con esos dos datos podes llamar al GetAuthorizeAnswer.

La pregunta final no la entedi, pero podes concatenar mas parametros en la url.
Slds!
