### ISSUE TITLE
Cuenta de vendedor invalida

### ISSUE THREAD

**Issue by richard015ar** [TodoPago/SDK-Node.js#14]
Al intentar hacer una llamada a sendAutorizeRequest obtengo siempre:
`{ StatusCode: 702,
  StatusMessage: 'Cuenta de vendedor invalida' }`

Estoy usando la API KEY que me figura en "Soluciones para vendedores".

**Comment by eazel7** [comment]
Mismo problema. Hay muchos errores. como 'MAXINSTALLMENTS' repetido.
@richard015ar vos pudiste hacer funcionar este 'SDK'?

**Comment by richard015ar** [comment]
Hola eazel7. Sii pude. Olvidate que te respondan aca, o por email. Son un desastre para dar soporte, lo termine solucionando yo solo.
Mi problema era que las dependencias no se estaban instalando.
Entrate a la carpeta donde descargaste el SDK, y corré npm install.

Suerte con esto!
Note: Actualmente estamos usando este SDK, porque no tenemos opción (no hay API pública) pero **no te lo recomiendo para nada**, es pésima y la documentación... terrible.

**Comment by eazel7** [comment]
@richard015ar me recomendás mirar algún otro SDK? el de .NET parece más prolijo pero igual de DIY para los requests. Hay alguno que esté bien?

**Comment by richard015ar** [comment]
La verdad que no se como funcionan los otros, solo usé éste.
Cosas que tenes que tener en cuenta (depende la implementación que vayas a hacer): 
- No existe el IPN en TodoPago
- Algunas respuestas que vienen de su API (y escupidas por el SDK, o sea imagino que en todos los SDKs porque usan la misma API), son incoherentes. Por ej: si hiciste una devolución, no te dice de que OPERATIONID o algun otro identificador único que te diga a qué pago corresponde esa devolución. 
- Las comisiones de los pagos se cargan tiempo después. Esto es, si se hace un pago, y queres devolverlo no podés excepto que esperes al menos 15 minutos aprox.
- Soporte pésimo.
- No hay notificaciones de las devoluciones.
- El operaionID que uses, va a ser usado automáticamente (y sin capacidad de personalizar) en el concepto del email del usuario. Por ej: si tu operationID es 13453, entonces al usuario le llega un mail diciendo: "Tu pago se acreditó. Concepto: 13453"

**Comment by FranciscoHanna** [comment]
El objeto parameters debe tener el atributo merchant en mayusculas y no como dice el ejemplo:
```javascript
var parameters = {
	...,
	'MERCHANT':XXXXX,
	...,
};
```

**Comment by geralvaredo** [comment]
@richard015ar buenas , la apikey en el codigo estaba mal, y estaba repetido el campo MAXINSTALLMENTS, en las proximas semanas será corregido. Gracias por el reporte. Saludos
