### ISSUE TITLE
Formulario Hibrido no devuelve AnswerKey

### ISSUE THREAD

**Issue by tferraro113** [TodoPago/SDK-Node.js#16]
## Comportamiento esperado
AnswerKey como parte de la resupuesta en la funcion "customPaymentSuccessResponse"

## Comportamiento actual
El objeto response sólo posee las siguientes propiedades : AuthorizationKey, ResultCode y ResultMessage.

## Pasos a reproducir
Luego de realizar una compra vía el formulario híbrido, al realizar un console log de la respuesta no figura el AnswerKey.

**Comment by geralvaredo** [comment]
@tferraro113 buenas tardes , quisiera saber si pudieron solucionar este tema? cualquier consulta dejo mi mail : galvaredo@prismamp.com
