### ISSUE TITLE
Devolución total y parcial no funcionan

### ISSUE THREAD

**Issue by tinchodias** [TodoPago/SDK-Node.js#3]
Con los ejemplos ```exampleReturnRequest``` y ```exampleVoidRequest``` obtengo status codes 702 así:

```
-------------------***-------------------
ReturnRequest
{ StatusCode: 702,
  StatusMessage: 'ERROR: Cuenta Inexistente',
  AuthorizationKey: {},
  AUTHORIZATIONCODE: {} }
null
-------------------***-------------------
```

También probé con datos de un pago generado por mi y fue similar.

**Comment by drarko** [comment]
Estimado, 
Los ejemplos son a titulo informativo, como muestra de uso y tipos de datos de las variables, no corresponden a datos reales.

La prueba que realizaste con tus datos ¿sobre que ambiente la realizaste? ¿Podrias pasarnos el fragmento de codigo?

Gracias

**Comment by tinchodias** [comment]
Hola, a continuación pego el código. Recibe como parámetros un RequestKey que acabo de crear y el MerchantId que usé. En Security puse un código usado en el send authorization. (BTW no sé que debería ir ahí)

```
function exampleVoidRequest(){

	var options = {
		endpoint : "developers",
		Authorization:'PRISMA f3d8b72c94ab4a06be2ef7c95490f7d3'
	};
	var parameters = {
		'Security': '1234567890ABCDEF1234567890ABCDEF',
		'Merchant': '2153',
		'RequestKey': '980c2821-feb3-58d1-414e-a6ac3413a466'
	};
	sdk.voidRequest(options, parameters, function(result, err){
		console.log("-------------------***-------------------");
		console.log("VoidRequest");
		console.log(result);
		console.log(err);
		console.log("-------------------***-------------------");
	});
}
```
(Copiado de ejemplo.js, donde solamente modifiqué los parámetros)

Raro, ahora estoy teniendo esta respuesta:
```
VoidRequest
{ StatusCode: 2013,
  StatusMessage: 'No es posible obtener los importes de las comisiones para realizar la devolucion',
  AuthorizationKey: {},
  AUTHORIZATIONCODE: {} }
null
```

Gracias por la respuesta rápida.

**Comment by drarko** [comment]
El codigo 2013 es respuesta del servicio. La SDK se esta pudiendo comunicar correctamente con TodoPago. 
Tene en cuenta que hay que esperar algunos minutos antes de poder realizar devoluciones.

Saludos

**Comment by tinchodias** [comment]
Gracias, sin embargo sería útil saber qué códigos se pueden esperar de resultado a la operación. Sobretodo para mi software sepa qué hacer de acuerdo a ese código devuelto, sin necesidad de que un humano lea el mensaje de error.

**Comment by tinchodias** [comment]
Vuelvo a este caso. Por más minutos que espero, no cambia el resultado.

**Comment by leosanmartin** [comment]
Hola.
Estoy en modo test y al realizar una devolución total recibo un error como el indicado.
 StatusCode: 2013,
  StatusMessage: 'No es posible obtener los importes de las comisiones para realizar la devolucion',
 Es una falla de TodoPago ?
o puedo estar fallando en el envio de datos necesarioa para realizar la devolucion.
