### ISSUE TITLE
Resultado inesperado en getStatus(): 702

### ISSUE THREAD

**Issue by tinchodias** [TodoPago/SDK-Node.js#4]
Buenas. Luego de haber autorizado un pago con `sendAuthorizeRequest `y `getAuthorizeAnswer`, ejecuto `getStatus` de acuerdo al ejemplo:

```
	var options = {
		endpoint : "developers",
		Authorization:'PRISMA f3d8b72c94ab4a06be2ef7c95490f7d3'
	};
	sdk.getStatus(options, '2153', '6061', function(result, err){
		console.log("-------------------***-------------------");
		console.log("getStatus result:");
		console.log(result);
		console.log("getStatus error:");
		console.log(err);
		console.log("-------------------***-------------------");
	});
```

Aclaro que tuve la precaución de usar el OPERATIONID=6061 para autorizar el pago. 

Obtengo por consola:

```
-------------------***-------------------
getStatus result:
{ Operations: undefined }
getStatus error:
null
-------------------***-------------------
```

Debuggeando a `todo-pago.j`s, encuentro que la respuesta a la llamada REST es un xml con `<Status>702</Status>`.
Mi problema es doble, no solo que `getStatus()` no devuelve lo esperado, sino que no hay ninguna referencia en la documentación de qué significa el código 702.

Muchas gracias por adelantado.

**Comment by drarko** [comment]
Estimado, revisaremos este incoveniente
Gracias

**Comment by tinchodias** [comment]
La respuesta es más clara en la nueva 1.2.0. Muchas gracias.

**Comment by nicolaspar** [comment]
Qué tal. Estoy teniendo el mismo código de Status (el 702) usando PHP. No encontré una guía de estos errores para saber que significa. Existe?
