### ISSUE TITLE
Respuesta inesperada y no documentada de getByRangeDateTime

### ISSUE THREAD

**Issue by tinchodias** [TodoPago/SDK-Node.js#5]
Buenas, perdón por el ruido pero hay un inconveniente con `getByRangeDateTime` también. Al ejecutar el ejemplo:

```
    var options = {
        endpoint : "developers",
        Authorization:'PRISMA f3d8b72c94ab4a06be2ef7c95490f7d3'
    };
    var parameters = {
        'MERCHANT': '2153',
        'STARTDATE': '2015-01-01T17:34:42.903',
        'ENDDATE': '2016-09-10T17:34:42.903'
    };

    sdk.getByRangeDateTime(options, parameters, function(result, err){
        console.log("-------------------***-------------------");
        console.log("GetByRangeDateTime");
        console.log(result);
        console.log(err);
        console.log("-------------------***-------------------");
    });
```

Obtengo en consola:

```
-------------------***-------------------
GetByRangeDateTime
{ Status: '1014' }
null
-------------------***-------------------
```

Lo cual no parece un resultado exitoso, y no sabemos qué significa 1014.

**Comment by peterpunk** [comment]
A mi me está dando otro número 702, pero no está funcionando este recurso.

**Comment by peterpunk** [comment]
Al achicar el rango de fecha pude obtener una respuesta válida. Los rangos de fehca no tienen que ser muy amplios, no está especificado el rango máximo que se puede utilizar en la consulta.

**Comment by gabybrow** [comment]
Probé con un rango pequeño y sigo teniendo el mismo problema. Si saben de algo avisen!!
Gracias!

**Comment by drarko** [comment]
Estimados,
 Se agrego un parámetro adicional al método.
 Por favor, referirse al ejemplo actualizado.
https://github.com/TodoPago/SDK-Node.js/blob/master/ejemplo/ejemplo.js#L144
 Gracias
