### ISSUE TITLE
getPaymentMethods Non-whitespace before first tag

### ISSUE THREAD

**Issue by marcosideame** [TodoPago/SDK-Node.js#6]
Hola!

Cuando estaba probando los métodos, en el método getPaymentMethods de todo-pago.js me daba el error 
"Non-whitespace before first tag"
la librería xml2js 

Para solucionarlo la dejé de usar y directamente node-rest-client me devuelve un json

`

getPaymentMethods: function(options, merchant, callback)  {

        var Client = require('node-rest-client').Client;
        client = new Client();

        client.get(endpoint[options.endpoint] + tenant + restAppend + "/PaymentMethods/Get/MERCHANT/" + merchant, function(data, response) {
            var ret = {
                'PaymentMethodsCollection': data.Result.PaymentMethodsCollection,
                'BanksCollection': data.Result.BanksCollection,
                'PaymentMethodBanksCollection': data.Result.PaymentMethodBanksCollection,
            };
            callback(ret, null);
        });

    }

`

No se, por ahora, si es la mejor forma pero para mis pruebas está bien

**Comment by marcosideame** [comment]
De hecho lo dejé así:

`getPaymentMethods: function(options, merchant) {
        return new Promise(function(resolve) {
            var axios = require('axios')
            var url = endpoint[options.endpoint] + tenant + restAppend + "/PaymentMethods/Get/MERCHANT/" + merchant
            return axios.get(url).then(function(res) {
                var data = res.data
                var ret = {
                    'PaymentMethodsCollection': data.Result.PaymentMethodsCollection,
                    'BanksCollection': data.Result.BanksCollection,
                    'PaymentMethodBanksCollection': data.Result.PaymentMethodBanksCollection,
                };
                return resolve(ret);
            });
        })
    },`

Porque me node-res-client me devolvía todo como array.

Saludos!

**Comment by alco4** [comment]
Hola Marcos, estamos intentando reproducir el error sin éxito, quizás podrías mandarnos mas información para así intentar hallar la raíz del problema? gracias

**Comment by alco4** [comment]
como la respuesta que te da el servicio con la solución que encontraste,

**Comment by alco4** [comment]
Hola Marcos, estamos intentando reproducir el error sin éxito, quizás podrías mandarnos mas información para así intentar hallar la raíz del problema? como la respuesta que te da el servicio con la solución que encontraste por ejemplo, gracias
