### ISSUE TITLE
Cannot find module 'todo-pago'

### ISSUE THREAD

**Issue by leiamac** [TodoPago/SDK-Node.js#7]
Instalé todo-pago mediante:
`$ npm install todo-pago --save`

Luego en mi archivo lo agregué de la siguiente manera:
`var todoPago = require("todo-pago");`

Sin embargo, al correr el script, tira el error "Cannot find module 'todo-pago'". La carpeta de todo-pago instalada tiene nada más un README y un package.json, así que por algún motivo no está instalandolo bien.

Luego probé descargando todo el repositorio y agregándolo manualmente a la carpeta de todo-pago creada, pero al correr el script (que lo único que hace es llamar a `getCredentials()`, aparece el siguiente error:
 `Cannot find module 'node-rest-client'`

Así que fui a la carpeta del módulo de todo-pago y corri npm install desde ahí. A partir de ahí no tuve más inconvenientes.

Por más de que pude resolver el problema, esta no es la manera en la que se debería instalar un módulo, Además, si alguien tiene el mismo problema que yo, puede ver esto y solucionarlo sin perder tiempo.

**Comment by elgambet** [comment]
Está desactualizado npm, pueden hacer un fork o directamente agregar la siguiente línea en su package.json y luego realizar npm install

`"todo-pago": "git+https://github.com/TodoPago/SDK-Node.js.git",`
