### ISSUE TITLE
Documentación o implementación de IPN

### ISSUE THREAD

**Issue by elgambet** [TodoPago/SDK-Node.js#8]
Hola, quería consultar si tienen algún servicio de notificaciones y donde encontrar la documentación de la misma.

En caso de que no posean [IPN](https://en.wikipedia.org/wiki/Instant_payment_notification) me gustaría preguntarles si tienen pensado agregarlo.

Dejo links a servicios parecidos:

[IPN mercadopago](https://www.mercadopago.com.ar/developers/es/api-docs/basic-checkout/ipn/)

[IPN paypal](https://developer.paypal.com/docs/classic/products/instant-payment-notification/)

Desde ya muchas gracias. Saludos.

**Comment by drarko** [comment]
Estimado, actualmente no manejamos IPN, la respuesta del pago es online y se consulta con el servicio GetAuthorizeAnswer.
Si deseas mas información sobre funcionalidades, por favor contactate a traves del formulario de contacto del sitio. 
Saludos

**Comment by emafriedrich** [comment]
Hola! tienen ipn ya?
