### ISSUE TITLE
getByRangeDateTime - { Status: '1014' }

### ISSUE THREAD

**Issue by elgambet** [TodoPago/SDK-Node.js#9]
getByRangeDateTime always returns { Status: '1014' }

Code example:

```
      var options = {
        endpoint : self.todopago.endpoint,
        Authorization: self.todopago.secret
      };

      var parameters = {
        'MERCHANT': self.todopago.merchant,
        'STARTDATE': '2017-01-16T10:00:00.000',
        'ENDDATE': '2017-01-25T22:00:00.000'
      };

      self.todopago.sdk.getByRangeDateTime(options, parameters, function(response, err){
          console.log("-------------------***-------------------");
          console.log("GetByRangeDateTime");
          console.log(response);
          // response is { Status: '1014' }
          console.log(err);
          console.log("-------------------***-------------------");
      });
```

**Comment by gabybrow** [comment]
Please, if you have any information of a solution for this issue, let me know.

**Comment by drarko** [comment]
Estimados,
Se agrego un parámetro adicional al método.
Por favor, referirse al ejemplo actualizado.
https://github.com/TodoPago/SDK-Node.js/blob/master/ejemplo/ejemplo.js#L144
Gracias

**Comment by gabybrow** [comment]
@drarko Gracias por la respuesta, pero me sigue devolviendo un objeto con un status distinto, y sigo sin obtener un array o un listado de las operaciones.

Saludos
